module.exports = {
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
    },
    colors: {
      transparent: 'rgba(255, 255, 255, 0)',
      black: '#000',
      white: {
        default: 'rgba(255, 255, 255, 1)',
        100: 'rgba(255, 255, 255, 0.1)',
        200: 'rgba(255, 255, 255, 0.2)',
        400: 'rgba(255, 255, 255, 0.4)',
        600: 'rgba(255, 255, 255, 0.6)',
        800: 'rgba(255, 255, 255, 0.8)',
        900: 'rgba(255, 255, 255, 0.9)',
      },
      gray: {
        default: 'rgba(16, 24, 32, 1)',
        100: 'rgba(0, 0, 0, 0.04)',
        200: 'rgba(0, 0, 0, 0.2)',
        400: 'rgba(0, 0, 0, 0.4)',
        600: 'rgba(0, 0, 0, 0.6)',
        800: 'rgba(0, 0, 0, 0.8)',
        900: 'rgba(0, 0, 0, 0.9)',
      },
      primary: {
        'default': 'rgb(195, 20, 37)',
        'darker': 'rgb(163, 0, 16)',
        '900': 'rgba(195, 20, 37, .9)',
        '800': 'rgba(195, 20, 37, .8)',
        '600': 'rgba(195, 20, 37, .6)',
        '400': 'rgba(195, 20, 37, .4)',
        '200': 'rgba(195, 20, 37, .2)',
        '100': 'rgba(195, 20, 37, .1)',
      },
      secondary: 'rgba(16, 24, 32, 1)',
      'secondary-200': 'rgba(16, 24, 32, .2)',
      'scrim': 'rgba(16, 24, 32, 0.8)',
    },
    spacing: {
      px: '1px',
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
    backgroundColor: theme => theme('colors'),
    backgroundPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'contain',
    },
    borderColor: theme => ({
      ...theme('colors'),
      default: theme('colors.gray.300', 'currentColor'),
    }),
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      default: '0.25rem',
      lg: '0.5rem',
      full: '9999px',
    },
    borderWidth: {
      default: '1px',
      '0': '0',
      '2': '2px',
      '4': '4px',
      '8': '8px',
    },
    boxShadow: {
      default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
      outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
      none: 'none',
    },
    container: {
      center: true,
    },
    cursor: {
      auto: 'auto',
      default: 'default',
      pointer: 'pointer',
      'not-allowed': 'not-allowed',
    },
    fill: {
      current: 'currentColor',
    },
    flex: {
      '1': '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none',
    },
    flexGrow: {
      '0': '0',
      default: '1',
    },
    flexShrink: {
      '0': '0',
      default: '1',
    },
    fontFamily: {
      display: [
        'AlternateGotNo1D',
      ],
      sans: [
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        'Eskorte',
        'Georgia',
        'Cambria',
        '"Times New Roman"',
        'Times',
        'serif',
      ],
    },
    fontSize: {
      xs: '0.875rem',
      sm: '1rem',
      base: '1.125rem',
      lg: '1.25rem',
      'xl': '1.5rem',
      '2xl': '1.875rem',
      '3xl': '2.25rem',
      '4xl': '3rem',
      '5xl': '4rem',
      '6xl': '5rem',
      '7xl': '6rem',
    },
    fontWeight: {
      hairline: '100',
      light: '300',
      normal: '400',
      bold: '700',
      black: '900',
    },
    height: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
    }),
    inset: {
      '0': '0',
      'pika': '-10px',
      auto: 'auto',
    },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
      widest: '0.1em',
      display: '0.2em',
      marketing: '0.3em',
    },
    lineHeight: {
      none: '1.25',
      tight: '1.375',
      snug: '1.5',
      normal: '1.625',
      relaxed: '2',
      loose: '2.5 ',
    },
    listStyleType: {
      none: 'none',
      disc: 'disc',
      decimal: 'decimal',
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing')),
    }),
    maxHeight: {
      full: '100%',
      screen: '100vh',
    },
    maxWidth: {
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      full: '100%',
    },
    minHeight: {
      '0': '0',
      '50vh': '50vh',
      '75vh': '75vh',
      full: '100%',
      screen: '100vh',
    },
    minWidth: {
      '0': '0',
      full: '100%',
    },
    objectPosition: {
      bottom: 'bottom',
      center: 'center',
      left: 'left',
      'left-bottom': 'left bottom',
      'left-top': 'left top',
      right: 'right',
      'right-bottom': 'right bottom',
      'right-top': 'right top',
      top: 'top',
    },
    opacity: {
      '0': '0',
      '25': '0.25',
      '50': '0.5',
      '75': '0.75',
      '100': '1',
    },
    order: {
      first: '-9999',
      last: '9999',
      none: '0',
      '1': '1',
      '2': '2',
      '3': '3',
      '4': '4',
      '5': '5',
      '6': '6',
      '7': '7',
      '8': '8',
      '9': '9',
      '10': '10',
      '11': '11',
      '12': '12',
    },
    padding: theme => theme('spacing'),
    stroke: {
      current: 'currentColor',
    },
    textColor: theme => theme('colors'),
    width: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.33333%',
      '2/3': '66.66667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.66667%',
      '2/6': '33.33333%',
      '3/6': '50%',
      '4/6': '66.66667%',
      '5/6': '83.33333%',
      '1/12': '8.33333%',
      '2/12': '16.66667%',
      '3/12': '25%',
      '4/12': '33.33333%',
      '5/12': '41.66667%',
      '6/12': '50%',
      '7/12': '58.33333%',
      '8/12': '66.66667%',
      '9/12': '75%',
      '10/12': '83.33333%',
      '11/12': '91.66667%',
      full: '100%',
      screen: '100vw',
      '40vw': '40vw',
    }),
    zIndex: {
      auto: 'auto',
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
    },
    gutenberg: theme => ({
      supports: {
        wideAlignments: true,
        wpGenerated: {
          fontSizes: true,
        },
      },
      screens: {
        'sm': theme('screens.sm'),
        'md': theme('screens.md'),
        'lg': theme('screens.lg'),
        'xl': theme('screens.xl'),
      },
      contentWidths: {
        xs: {
          normal: theme('maxWidth.xl'),
          wide: theme('maxWidth.full'),
          full: theme('maxWidth.full'),
        },
        sm: {
          normal: theme('maxWidth.2xl'),
          wide: theme('maxWidth.full'),
          full: theme('maxWidth.full'),
        },
        md: {
          normal: theme('maxWidth.3xl'),
          wide: theme('maxWidth.4xl'),
          full: theme('maxWidth.full'),
        },
        lg: {
          normal: theme('maxWidth.4xl'),
          wide: theme('maxWidth.5xl'),
          full: theme('maxWidth.full'),
        },
        xl: {
          normal: theme('maxWidth.5xl'),
          wide: theme('maxWidth.6xl'),
          full: theme('maxWidth.full'),
        },
      },
      colors: {
        'native-scarlet': theme('colors.primary.default'),
        'kuroi': theme('colors.secondary'),
      },
      fontFamily: {
        'h1': theme('fontFamily.display'),
        'h2': theme('fontFamily.display'),
        'h3': theme('fontFamily.display'),
        'h4': theme('fontFamily.display'),
        'h5': theme('fontFamily.display'),
        'h6': theme('fontFamily.display'),
        'p': theme('fontFamily.serif'),
        'ul': theme('fontFamily.serif'),
        'ol': theme('fontFamily.serif'),
        'table': theme('fontFamily.sans'),
      },
      fontSizes: {
        'h1': theme('fontSize.6xl'),
        'h2': theme('fontSize.3xl'),
        'h3': theme('fontSize.2xl'),
        'h4': theme('fontSize.xl'),
        'h5': theme('fontSize.lg'),
        'h6': theme('fontSize.lg'),
        'ol': theme('fontSize.base'),
        'ul': theme('fontSize.base'),
        'p': theme('fontSize.base'),
        // wordpress generated fontsizes
        wpGenerated: {
          small: '12px',
          normal: '16px',
          large: '36px',
          huge: '50px',
        },
      },
      images: {},
      /**
       * Keys for `gutenberg.figCaption.textAlign`
       * map to the alignment of the containing block
       */
      figCaption: {
        align: {
          left: 'left',
          right: 'right',
          center: 'center',
          wide: 'center',
        },
        fontFamily: theme('fontFamily.sans'),
        fontSize: theme('fontSize.xs'),
      },
      lists: {
        unorderedStyle: 'square',
        orderedStyle: 'lower-roman',
        inset: theme('spacing.2'),
      },
      columnGap: theme('spacing.2'),
      rowGap: {
        default: theme('spacing.8'),
        wide: theme('spacing.12'),
        full: theme('spacing.16'),
        spacious: theme('spacing.16'),
      },
      blocks: {
        cover: {
          verticalPadding: theme('spacing.64'),
        },
      },
    }),
  },
  variants: {
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['hover', 'focus'],
    backgroundPosition: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['hover', 'focus'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['hover'],
    boxShadow: ['hover', 'focus'],
    display: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontSmoothing: [],
    fontStyle: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive', 'hover'],
    opacity: ['responsive'],
    order: ['responsive'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    pointerEvents: [],
    position: ['responsive', 'hover'],
    resize: [],
    tableLayout: [],
    textAlign: ['responsive'],
    textColor: ['hover', 'focus'],
    textDecoration: ['hover', 'focus'],
    textTransform: [],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive'],
  },
  corePlugins: {},
  plugins: [
    require('glhd-tailwindcss-transitions').default({
      transitionPrefix: '.transition',
      transitionVariants: [],
      transitionDuration: {
        'default': '.2s',
        'slow': '.5s',
        'fast': '.15s',
      },
      transitionProperty: {
        'default': 'all',
        'all': 'all',
        'none': 'none',
        'bg': 'background',
        'opacity': 'opacity',
        'color': 'color',
        'shadow': 'box-shadow',
      },
      transitionTimingFunction: {
        'default': 'ease-in-out',
        'ease-in-out': 'ease-in-out',
      },
      transitionDelay: {
        'default': '.1s',
        'long': '.2s',
        'none': '0s',
      },
    }),
  ],
}
