##
# Tiny Pixel Deployment Workflows
#
# CircleCI
#   @see https://circleci.com/docs/2.0/using-orbs/
#
# itinerisltd/tiller-circleci
#   @see https://circleci.com/orbs/registry/orb/itinerisltd/tiller-circleci
#
# picturepipe/sentry-cli
#   @see https://circleci.com/orbs/registry/orb/picturepipe/sentry-cli
#
# cypress-io/cypress
#   @see https://circleci.com/orbs/registry/orb/cypress-io/cypress
#
# percy/agent
#   @see https://docs.percy.io/docs/circleci#section-parallelized-tests-configuring-your-circle-ci-orb
##
version: 2.1

orbs:
  tiller-circleci: itinerisltd/tiller-circleci@0.5
  sentry-cli: picturepipe/sentry-cli@1.1.1
  cypress: cypress-io/cypress@1

executors:
  php-73:
    docker:
      - image: circleci/php:7.3-stretch

workflows:
  deploy:
    jobs:
      # Hold build for approval
      - hold:
          type: approval
          filters:
            branches:
              only:
                - staging
                - master

      # Cypress pre-integration specs
      - cypress/run:
          executor: cypress/browsers-chrome69
          name: integration-pre-deploy
          browser: chrome
          yarn: true
          spec: cypress/integration/staging.spec.js
          requires:
            - hold
          filters:
            branches:
              only:
                - master

      # Deploy staging
      - tiller-circleci/deploy:
          name: deploy-staging
          known_hosts: 'github.com, 165.22.190.49'
          trellis_repo: 'git@github.com:pixelcollective/managed-wordpress-deploy.dev.git'
          site_env: staging
          site_name: tinypixel.dev
          executor: tiller-circleci/ansible-27
          requires:
            - hold
          filters:
            branches:
              only:
                - staging

      # Deploy production
      - tiller-circleci/deploy:
          name: deploy-production
          known_hosts: 'github.com, 157.230.209.152'
          trellis_repo: 'git@github.com:pixelcollective/managed-wordpress-deploy.dev.git'
          site_env: production
          site_name: tinypixel.dev
          executor: tiller-circleci/ansible-27
          requires:
            - integration-pre-deploy
          filters:
            branches:
              only:
                - master

      # Sentry checkout staging
      - sentry-cli/checkout-to-workspace:
          name: sentry-checkout-staging
          requires:
            - deploy-staging
          filters:
            branches:
              only:
                - staging

      # Sentry checkout production
      - sentry-cli/checkout-to-workspace:
          name: sentry-checkout-production
          requires:
            - deploy-production
          filters:
            branches:
              only:
                - master

      # Sentry set version staging
      - sentry-cli/set-version:
          name: sentry-version-staging
          requires:
            - sentry-checkout-staging
          filters:
            branches:
              only:
                - staging

      # Sentry set version production
      - sentry-cli/set-version:
          name: sentry-version-production
          requires:
            - sentry-checkout-production
          filters:
            branches:
              only:
                - master

      # Sentry create release staging
      - sentry-cli/create-release:
          name: sentry-create-release-staging
          requires:
            - sentry-version-staging
          filters:
            branches:
              only:
                - staging

      # Sentry create release production
      - sentry-cli/create-release:
          name: sentry-create-release-production
          requires:
            - sentry-version-production
          filters:
            branches:
              only:
                - master

      # Sentry finalize release staging
      - sentry-cli/finalize-release-set-commits:
          name: sentry-finalize-release-staging
          requires:
            - sentry-create-release-staging
          filters:
            branches:
              only:
                - staging

      # Sentry finalize release production
      - sentry-cli/finalize-release-set-commits:
          name: sentry-finalize-release-production
          requires:
            - sentry-create-release-production
          filters:
            branches:
              only:
                - master

      # Sentry create deployment
      - sentry-cli/create-deployment:
          name: sentry-deploy-staging
          env: staging
          requires:
            - sentry-finalize-release-staging
          filters:
            branches:
              only:
                - staging

      # Sentry create deployment production
      - sentry-cli/create-deployment:
          name: sentry-deploy-production
          env: production
          requires:
            - sentry-finalize-release-production
          filters:
            branches:
              only:
                - master

      # Cypress post-deployment specs staging
      - cypress/run:
          name: integration-post-deploy-staging
          executor: cypress/browsers-chrome69
          browser: chrome
          yarn: true
          record: true
          spec: cypress/integration/staging.spec.js
          command: 'yarn percy:staging'
          requires:
            - sentry-deploy-staging
          filters:
            branches:
              only:
                - staging

      # Cypress post-deployment specs production
      - cypress/run:
          name: integration-post-deploy-production
          executor: cypress/browsers-chrome69
          requires:
            - sentry-deploy-production
          browser: chrome
          yarn: true
          record: true
          spec: cypress/integration/production.spec.js
          filters:
            branches:
              only:
                - master
