version: 2.1

orbs:
  tiller-circleci: itinerisltd/tiller-circleci@3.2.0
  sentry-cli: picturepipe/sentry-cli@1.1.1

executors:
  php-73:
    docker:
      - image: circleci/php:7.4-stretch
  node-12:
    docker:
      - image: itinerisltd/tiller-circleci:node-14

workflows:
  deploy:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - staging
                - master

      - tiller-circleci/deploy:
          name: deploy-staging
          known-hosts: 'github.com, 165.22.190.49'
          trellis-repo: 'git@github.com:pixelcollective/trellis.git'
          site-env: staging
          site-name: dreamdefenders.org
          executor-tag: node-12
          vault-password: VAULT_PASSWORD
          requires:
            - hold
          filters:
            branches:
              only:
                - staging

      - tiller-circleci/deploy:
          name: deploy-production
          known-hosts: 'github.com, 157.230.209.152'
          trellis-repo: 'git@github.com:pixelcollective/trellis.git'
          site-env: 'production'
          site-name: dreamdefenders.org
          executor-tag: node-12
          vault-password: VAULT_PASSWORD
          requires:
            - hold
          filters:
            branches:
              only:
                - master
