wordpress_sites:
  data.dreamdefenders.org:
    site_hosts:
      - canonical: data.dreamdefenders.tinypixel.dev
    local_path: ../bedrock
    repo: git@github.com:pixelcollective/dreamdefenders.org
    repo_subtree_path: bedrock
    branch: staging-server
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: true
